# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='return',
            name='borrower_name',
        ),
        migrations.RemoveField(
            model_name='return',
            name='isbn_no',
        ),
    ]
